"""add savings_account_id column Expenses

Revision ID: 3c48ced5f97f
Revises: a6b0a3b3637d
Create Date: 2026-01-16 19:54:44.810218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c48ced5f97f'
down_revision: Union[str, Sequence[str], None] = 'a6b0a3b3637d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('savings_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_savings_account_id'), 'expenses', ['savings_account_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'savings_accounts', ['savings_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_savings_account_id'), table_name='expenses')
    op.drop_column('expenses', 'savings_account_id')
    # ### end Alembic commands ###
