"""Initial migration - create all tables

Revision ID: a6b0a3b3637d
Revises: 
Create Date: 2026-01-13 16:06:19.127387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b0a3b3637d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_payment_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('available_credit >= 0 AND available_credit <= credit_limit', name='check_valid_available_credit'),
    sa.CheckConstraint('credit_limit > 0', name='check_positive_credit_limit'),
    sa.CheckConstraint('outstanding_balance >= 0', name='check_positive_outstanding'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_card_number'), 'credit_cards', ['card_number'], unique=True)
    op.create_index(op.f('ix_credit_cards_id'), 'credit_cards', ['id'], unique=False)
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('savings_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('minimum_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_balance >= 0', name='check_positive_balance'),
    sa.CheckConstraint('minimum_balance >= 0', name='check_positive_min_balance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_accounts_account_number'), 'savings_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_savings_accounts_id'), 'savings_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_savings_accounts_user_id'), 'savings_accounts', ['user_id'], unique=False)
    op.create_table('credit_card_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_purchases', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_payments', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('minimum_payment_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_statements_credit_card_id'), 'credit_card_statements', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_credit_card_statements_due_date'), 'credit_card_statements', ['due_date'], unique=False)
    op.create_index(op.f('ix_credit_card_statements_id'), 'credit_card_statements', ['id'], unique=False)
    op.create_index(op.f('ix_credit_card_statements_statement_date'), 'credit_card_statements', ['statement_date'], unique=False)
    op.create_table('credit_card_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount != 0', name='check_nonzero_amount'),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_transactions_credit_card_id'), 'credit_card_transactions', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_credit_card_transactions_id'), 'credit_card_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_credit_card_transactions_transaction_date'), 'credit_card_transactions', ['transaction_date'], unique=False)
    op.create_table('debit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('savings_account_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['savings_account_id'], ['savings_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debit_cards_card_number'), 'debit_cards', ['card_number'], unique=True)
    op.create_index(op.f('ix_debit_cards_id'), 'debit_cards', ['id'], unique=False)
    op.create_index(op.f('ix_debit_cards_savings_account_id'), 'debit_cards', ['savings_account_id'], unique=False)
    op.create_index(op.f('ix_debit_cards_user_id'), 'debit_cards', ['user_id'], unique=False)
    op.create_table('savings_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('savings_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['savings_account_id'], ['savings_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_transactions_id'), 'savings_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_savings_transactions_savings_account_id'), 'savings_transactions', ['savings_account_id'], unique=False)
    op.create_index(op.f('ix_savings_transactions_transaction_date'), 'savings_transactions', ['transaction_date'], unique=False)
    op.create_table('credit_card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('savings_account_id', sa.Integer(), nullable=True),
    sa.Column('savings_transaction_id', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_before', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('payment_amount > 0', name='check_positive_payment'),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['savings_account_id'], ['savings_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['savings_transaction_id'], ['savings_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_payments_credit_card_id'), 'credit_card_payments', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_credit_card_payments_id'), 'credit_card_payments', ['id'], unique=False)
    op.create_index(op.f('ix_credit_card_payments_payment_date'), 'credit_card_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_credit_card_payments_savings_account_id'), 'credit_card_payments', ['savings_account_id'], unique=False)
    op.create_index(op.f('ix_credit_card_payments_savings_transaction_id'), 'credit_card_payments', ['savings_transaction_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('debit_card_id', sa.Integer(), nullable=True),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.Column('credit_card_transaction_id', sa.Integer(), nullable=True),
    sa.Column('savings_transaction_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_expense_amount'),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_card_transaction_id'], ['credit_card_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debit_card_id'], ['debit_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['savings_transaction_id'], ['savings_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_credit_card_id'), 'expenses', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_expenses_credit_card_transaction_id'), 'expenses', ['credit_card_transaction_id'], unique=False)
    op.create_index(op.f('ix_expenses_debit_card_id'), 'expenses', ['debit_card_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_savings_transaction_id'), 'expenses', ['savings_transaction_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_savings_transaction_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_debit_card_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_credit_card_transaction_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_credit_card_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_credit_card_payments_savings_transaction_id'), table_name='credit_card_payments')
    op.drop_index(op.f('ix_credit_card_payments_savings_account_id'), table_name='credit_card_payments')
    op.drop_index(op.f('ix_credit_card_payments_payment_date'), table_name='credit_card_payments')
    op.drop_index(op.f('ix_credit_card_payments_id'), table_name='credit_card_payments')
    op.drop_index(op.f('ix_credit_card_payments_credit_card_id'), table_name='credit_card_payments')
    op.drop_table('credit_card_payments')
    op.drop_index(op.f('ix_savings_transactions_transaction_date'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_savings_account_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_id'), table_name='savings_transactions')
    op.drop_table('savings_transactions')
    op.drop_index(op.f('ix_debit_cards_user_id'), table_name='debit_cards')
    op.drop_index(op.f('ix_debit_cards_savings_account_id'), table_name='debit_cards')
    op.drop_index(op.f('ix_debit_cards_id'), table_name='debit_cards')
    op.drop_index(op.f('ix_debit_cards_card_number'), table_name='debit_cards')
    op.drop_table('debit_cards')
    op.drop_index(op.f('ix_credit_card_transactions_transaction_date'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_id'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_credit_card_id'), table_name='credit_card_transactions')
    op.drop_table('credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_statements_statement_date'), table_name='credit_card_statements')
    op.drop_index(op.f('ix_credit_card_statements_id'), table_name='credit_card_statements')
    op.drop_index(op.f('ix_credit_card_statements_due_date'), table_name='credit_card_statements')
    op.drop_index(op.f('ix_credit_card_statements_credit_card_id'), table_name='credit_card_statements')
    op.drop_table('credit_card_statements')
    op.drop_index(op.f('ix_savings_accounts_user_id'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_id'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_account_number'), table_name='savings_accounts')
    op.drop_table('savings_accounts')
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_card_number'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
